### ISSUE TITLE
org.slf4j.impl.StaticLoggerBinder error from `generate`

### ISSUE THREAD

**Issue by kevingessner** [johnynek/bazel-deps#55]
I consistently see this warning when I run `generate` (tested @ 1ec2d84e172644ea2c8735b5b10bb783e5020d42):

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I've seen this on both linux and OS X.  Can that missing dependency be added so the correct logs are written and the error is suppressed?

**Comment by johnynek** [comment]
yeah, I think that we are missing a dependency in the binary. I guess we need the jar in the binary that has StaticLoggerBinder?

**Comment by PaulAtBanno** [comment]
Ironically, I was just going to add this.

The problem is that I was going to add it because I hoped to get some log output to help track down a failure to download an artifact... but when I tried to bootstrap bazel_deps, it failed to download logback-classic. Naturally.

I may look into the Coursier issue next... :-)

**Comment by johnynek** [comment]
@paulatbano that would be great!

I think @non may have a branch where he started that. Am I misremembering?
